### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by wanghepu** [iErcann/enari-engine#1]
![image](https://github.com/iErcann/enari-engine/assets/57623763/8bec52f0-8d33-4f0c-a53c-391678e75c2f)
can you tell me your node version，it run with error on my PC

**Comment by iErcann** [comment]
I'm using Node.js v20.11.1, it also works with v18.17.1, what's your version?

**Comment by wanghepu** [comment]
> I'm using Node.js v20.11.1, it also works with v18.17.1, what's your version?
thank you very much,my node version is v16.13,the code maybe has problem，LoadableMesh.ts line  30，and the threejs version has problem too，the code using BoxBufferedGemerty but v162 changed，It is working on my PC after I changed the code
